Repository Ludo-SMP/ludo-frontend, pull requests merged in 2024-07, with the labels that each got.

#303 SP-633 스터디/모집공고 임시저장 기능 구현 및 셀렉트 초기화 로직 리팩토링
  README.md
  package.json
  src/Apis/study.ts
  src/Components/AlarmInBox/index.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Common/Divider/RowDivider/index.tsx
  src/Components/Common/FormSection/index.tsx
  src/Components/Common/Grid/index.tsx
  src/Components/CustomSelect/CustomSelect.spec.tsx
  src/Components/CustomSelect/CustomSelect.stories.ts
  src/Components/CustomSelect/CustomSelect.tsx
  src/Components/Header/AlarmBell/index.tsx
  src/Components/Header/index.tsx
  src/Components/Sidebar/Sidebar.tsx
  src/Components/Sidebar/Tab.tsx
  src/Constants/messages.ts
  src/Hooks/recruitments/useCreateRecruitment.ts
  src/Hooks/recruitments/useSelectDefaultValue.ts
  src/Hooks/useAttendanceModal.ts
  src/Hooks/useStack.ts
  src/Hooks/useTempSaved.ts
  src/Pages/CreateRecruitment/index.tsx
  src/Pages/CreateRecruitment/layout.tsx
  src/Pages/CreateRecruitment/page.tsx
  src/Pages/EditRecruitment/EditRecruitmentFetcher.tsx
  src/Pages/EditRecruitment/index.tsx
  src/Pages/MyPage/UserInfoSection.tsx
  src/Pages/Notifications/index.tsx
  src/Pages/NotificationsSettings/KeywordsSettingForm.tsx
  src/Pages/Studies/CreateButtons.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/EditButtons.tsx
  src/Pages/Studies/EditStudy.tsx
  src/Pages/Studies/Layout.tsx
  src/Router/index.tsx
  src/Shared/study.ts
  src/Types/study.ts
  src/utils/date.ts
  src/utils/selectUtil.ts
  vite.config.ts
Labels: 모집공고생성, API, 스터디 수정

#305 SP-651 Footer 수정된 디자인 반영, 스터디 모집공고 페이지 반응형 구현
  src/Assets/LeftArrow.tsx
  src/Components/Banner/index.tsx
  src/Components/Common/Button/index.tsx
  src/Components/Footer/index.tsx
  src/Components/UtilityButtons/MobileUtilityButton/index.tsx
  src/Layout/MyPageLayout.tsx
  src/Pages/Login/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/Notifications/index.tsx
  src/Pages/RecruitmentDetail/ApplySection.tsx
  src/Pages/RecruitmentDetail/RecruitInfoSection.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/SignUp/index.tsx
Labels: 🖌 style, 📄 모집공고 상세

#308 SP-652 스터디원 상호 리뷰 관련 버그 수정
  src/Assets/Profile.tsx
  src/Components/ReviewScore/ReviewScore.stories.ts
  src/Components/ReviewScore/StarScore/StarScore.stories.ts
  src/Components/ReviewScore/StarScore/index.tsx
  src/Components/ReviewScore/index.tsx
  src/Components/StudyReviews/PeerToPeerReview/PeerToPeerReview.stories.ts
  src/Components/StudyReviews/PeerToPeerReview/Review/Review.stories.ts
  src/Components/StudyReviews/PeerToPeerReview/Review/index.tsx
  src/Components/StudyReviews/PeerToPeerReview/index.tsx
  src/Components/StudyReviews/index.tsx
  src/Components/Topbar/index.tsx
Labels: 스터디원 리뷰

#315 fix: 스터디 모집 공고 버튼 숨김
  src/Pages/RecruitmentDetail/ApplySection.tsx
Labels: 🙋🏻‍♂️ 스터디 지원

#321 fix: `<CircularRate />` 소수점 생략
  src/Components/CircularRate/CircularRate.spec.tsx
  src/Components/CircularRate/index.tsx
Labels: bug

#326 feat: 사용자 프로필 사진 Gravatar 표시
  package.json
  src/Assets/Profile.stories.ts
  src/Assets/Profile.tsx
  src/Components/ApplicantCard/index.tsx
  src/Components/Header/index.tsx
  src/Components/MemberProfile/index.tsx
  src/Components/ProfileSection/ProfileSection.tsx
  yarn.lock
Labels: 👤 회원정보, 🙋🏻‍♂️ 스터디 지원, 📋 스터디 상태, storybook, 사용자 신뢰도

#330 fix: 평균 출석률 자릿수 고정
  src/Pages/MyPage/UserInfoSection.tsx
Labels: 👩‍🎨 마이페이지

#331 fix: 스터디 종료, 또는 스터디장의 경우 탈퇴 불가
  src/Components/MemberProfile/index.tsx
Labels: 🏃 스터디 탈퇴

#332 feat: 리뷰 페이지 리뷰이 데이터 바인딩
  src/Pages/Review/index.tsx
Labels: 사용자 리뷰평가, 스터디원 리뷰

#333 feat: 출석일을 제외한 날에는 출석 버튼 비활성화
  src/Pages/StudyDetail/index.tsx
  src/Shared/study.ts
  src/Types/atoms.ts
  src/Types/study.ts
  src/utils/date.ts
Labels: 자동 출석 체크

#334 플레이스홀더 이미지 배치
  src/Pages/MyPage/StudiesSection.tsx
Labels: 👩‍🎨 마이페이지

#336 release: dev -> main 배포
  package.json
  src/Assets/Profile.stories.ts
  src/Assets/Profile.tsx
  src/Assets/images/character4.png
  src/Assets/index.tsx
  src/Components/ApplicantCard/index.tsx
  src/Components/ErrorBoundary/index.tsx
  src/Components/Header/Gnb/GnbMenu/index.tsx
  src/Components/Header/index.tsx
  src/Components/MemberProfile/index.tsx
  src/Components/Modal/EditProfileModal/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Components/ProfileSection/ProfileSection.tsx
  src/Components/ProfileSection/SettingButton.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Components/StudyReviews/PeerToPeerReview/Review/index.tsx
  src/Components/UTbanner/index.tsx
  src/Constants/messages.ts
  src/Hooks/useAttendanceModal.ts
  src/Mocks/data/mockMypage.ts
  src/Pages/MyPage/StudiesSection.tsx
  src/Pages/MyPage/UserInfoSection.tsx
  src/Pages/MyPageReviews/index.tsx
  src/Pages/Notifications/index.tsx
  src/Pages/RecruitmentDetail/ApplySection.tsx
  src/Pages/Review/index.tsx
  src/Pages/Saved/index.tsx
  src/Pages/Studies/Layout.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/Shared/study.ts
  src/Types/atoms.ts
  src/Types/study.ts
  src/utils/date.ts
  yarn.lock
Labels: 🎬 배포

#339 fix/applicants additionals
  src/Hooks/study/useAcceptApplyMutation.ts
  src/Pages/Applicants/index.tsx
Labels: 🙋🏻‍♂️ 스터디 지원

#341 feat: 모집공고가 없을 시, 지원자 페이지에서 모집공고 생성 버튼 표시
  src/Pages/Applicants/index.tsx
Labels: 🙋🏻‍♂️ 스터디 지원, 👥 스터디 모집

#343 fix: 브라우저 경고 발생시키는 prop 이름 관련 이슈 해결
  src/Assets/LeftArrow.tsx
  src/Components/Common/InfoField/index.tsx
Labels: bug

#344 7월 5일 프로덕션 2차 재배포 진행
  src/Assets/LeftArrow.tsx
  src/Components/Common/InfoField/index.tsx
  src/Pages/Applicants/index.tsx
  src/Pages/StudyDetail/index.tsx
Labels: 🎬 배포

#345 hotFix: 7/5(화) 회의 건의사항 반영
  package.json
  src/Components/Common/InputText/index.tsx
  src/Constants/common.ts
  src/Hooks/notifications/useReadNotification.ts
  src/Pages/Applicants/index.tsx
  src/Pages/CreateRecruitment/layout.tsx
  src/Pages/EditRecruitment/index.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection.tsx
  src/Pages/StudyDetail/index.tsx
  src/Styles/globalStyles.ts
  vite.config.ts
  yarn.lock
Labels: bug

#346 release: dev -> main 배포
  package.json
  src/Components/Common/InputText/index.tsx
  src/Constants/common.ts
  src/Hooks/notifications/useReadNotification.ts
  src/Pages/Applicants/index.tsx
  src/Pages/CreateRecruitment/layout.tsx
  src/Pages/EditRecruitment/index.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection.tsx
  src/Pages/StudyDetail/index.tsx
  src/Styles/globalStyles.ts
  vite.config.ts
  yarn.lock
Labels: 🎬 배포

#347 release: dev -> main 배포
  src/Apis/recruitment.ts
  src/Constants/api.ts
  src/Hooks/recruitments/useEditRecruitment.ts
  src/Pages/EditRecruitment/index.tsx
  src/Pages/RecruitmentDetail/ApplySection.tsx
Labels: 🎬 배포
