Repository Ludo-SMP/ludo-frontend, pull requests merged in 2024-01, with the labels that each got.

#5 GlobalStyle 사용 설정 및 기본적인 디자인 속성 설정 완료
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/Styles/globalStyles.ts
  src/Styles/styled.d.ts
  src/Styles/theme.ts
  vite.config.ts
  yarn.lock
Labels: style

#7 feat: 라우터 &메인페이지 구획나누기 & svg 컴포넌트 구현
  src/App.tsx
  src/Assets/Alarm.tsx
  src/Assets/Hamberger.tsx
  src/Components/Button/FilterButton.tsx
  src/Components/Button/StudyButton.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Header/Header.tsx
  src/Constants/Router_Path.tsx
  src/Constants/styled.tsx
  src/Layout/MainLayout.tsx
  src/Pages/Main.tsx
  src/Router/index.tsx
  src/Styles/styled.d.ts
  src/Styles/theme.ts
  src/Types/type.tsx
  src/main.tsx
  yarn.lock
Labels: 라우팅

#8 Feat: 메인페이지 헤더, 햄버거바, 알람,버튼 마크업 구현
  src/Components/Button/StudyButton.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Header/Header.tsx
  src/Components/Profile/Profile.tsx
  src/Pages/Main.tsx
  src/Styles/styled.d.ts
  src/Styles/theme.ts
Labels: 마크업

#9 메인페이지 UI 마크업 구현 완료
  package.json
  src/Components/Banner/index.tsx
  src/Components/StudyCard/Position/index.tsx
  src/Components/StudyCard/Tool/index.tsx
  src/Components/StudyCard/index.tsx
  src/Components/StudyCardList/index.tsx
  src/Pages/Main.tsx
  src/Shared/dummy.ts
  src/Styles/styled.d.ts
  src/Styles/theme.ts
  src/assets/icons/right-bold.svg
  vite.config.ts
  yarn.lock
Labels: 마크업, 리팩토링

#14 스터디 상세 페이지 UI 마크업 구현 완료
  src/Assets/icons/RightBold.tsx
  src/Components/Common/BlankSquare/index.tsx
  src/Components/Common/Divider/ColumnDivider/index.tsx
  src/Components/Common/Divider/RowDivider/index.tsx
  src/Components/Common/InfoField/index.tsx
  src/Components/MemberProfile/index.tsx
  src/Constants/Router_Path.tsx
  src/Pages/Main.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/Styles/styled.d.ts
  src/Styles/theme.ts
Labels: 마크업

#16 Feat: 스터디 생성,수정 모집공고 생성 마크업
  src/App.tsx
  src/Assets/Calendar.tsx
  src/Assets/LeftArrow.tsx
  src/Assets/RightArrow.tsx
  src/Assets/SelectArrow.tsx
  src/Components/Button/Studies/CalendarButton.tsx
  src/Components/Button/Studies/ContactButton.tsx
  src/Components/Button/Studies/PlatformButton.tsx
  src/Components/Button/Studies/ProgressButton.tsx
  src/Components/Button/Studies/StackButton.tsx
  src/Components/Button/Studies/SubmitButton.tsx
  src/Components/Button/StudyButton.tsx
  src/Components/Calendar/Calendar.tsx
  src/Components/Common/BlankSquare/index.tsx
  src/Components/Header/BackHeader.tsx
  src/Components/MemberProfile/index.tsx
  src/Components/Textarea/Mainarea.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Constants/Router_Path.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/GatherStudy.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/assets/icons/right-bold.svg
Labels: 마크업, 라우팅

#22 Feat: 캘린더, 기술스택 모달, 조건에 따라 헤더 바꾸기 구현
  index.html
  package.json
  src/App.tsx
  src/Assets/Calendar.tsx
  src/Assets/SearchIcon.tsx
  src/Components/Button/Studies/CalendarButton.tsx
  src/Components/Button/Studies/StackButton.tsx
  src/Components/Button/StudyButton.tsx
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Header/BackHeader.tsx
  src/Components/Header/Header.tsx
  src/Components/Header/HeaderButton/MediumButton.tsx
  src/Components/Header/HeaderButton/SmallButton.tsx
  src/Components/Header/MainHeader.tsx
  src/Components/Modal/DefaultModal.tsx
  src/Components/Modal/ModalContent/FilterContent.tsx
  src/Components/Modal/ModalContent/ModalButton/CancelButton.tsx
  src/Components/Modal/ModalContent/ModalButton/SelectButton.tsx
  src/Components/Modal/ModalContent/ModalContainer.tsx
  src/Components/Modal/ModalContent/ModalContent.tsx
  src/Components/Modal/ModalContent/SearchBar.tsx
  src/Components/Modal/ModalContent/StackContent.tsx
  src/Components/Modal/StackModal.tsx
  src/Hooks/useOutsideClick.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/GatherStudy.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Router/index.tsx
  src/Styles/styled.d.ts
  src/Styles/theme.ts
  src/main.tsx
  yarn.lock
Labels: 마크업, 라우팅

#21 MSW를 활용한 API Mocking 환경 구성 완료
  .gitignore
  package.json
  public/mockServiceWorker.js
  src/Apis/study.ts
  src/Mocks/browser.ts
  src/Mocks/data/mockData.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/study.ts
  src/Pages/StudyList/index.tsx
  src/main.tsx
  yarn.lock
Labels: 환경설정, mocking
