Repository Ludo-SMP/ludo-frontend, pull requests merged in 2024-06, with the labels that each got.

#214 SP-578 스터디 디테일 페이지 2.0 UI 구현
  package.json
  src/Components/Common/Button/ApplicationButton/ApplicationButton.stories.ts
  src/Components/Common/Button/ApplicationButton/ApplicationButton.tsx
  src/Components/MemberProfile/index.tsx
  src/Pages/StudyDetail/MemberSection.tsx
  src/Pages/StudyDetail/MemberSection/MemberCarousel/index.tsx
  src/Pages/StudyDetail/MemberSection/index.tsx
  src/Pages/StudyDetail/Sidebar.tsx
  src/Pages/StudyDetail/StudyInfoSection/index.tsx
  src/Pages/StudyDetail/index.tsx
  yarn.lock
Labels: 마크업, 🖌 style, 리팩토링, 📋 스터디 상태

#224 SP-567 리뷰 작성 페이지
  src/Components/CustomRadio/CustomRadio.tsx
  src/Components/ReviewQuestion/ReviewQuestion.stories.ts
  src/Components/ReviewQuestion/ReviewQuestion.tsx
  src/Constants/route.ts
  src/Pages/Review/index.tsx
  src/Router/index.tsx
Labels: 사용자 리뷰평가

#227 SP-599 회원정보 및 임시저장된 글 2.0 UI 구현
  src/Components/Common/Divider/RowDivider/RowDivider.stories.ts
  src/Components/Common/Divider/RowDivider/index.tsx
  src/Components/Profile/Profile.stories.ts
  src/Components/Profile/Profile.tsx
  src/Components/ProfileSection/ProfileSection.tsx
  src/Components/ProfileSection/SettingButton.tsx
  src/Components/UserCard/UserCard.stories.tsx
  src/Components/UserCard/index.tsx
  src/Layout/MainLayout.tsx
  src/Pages/MyPage/StudiesSection.tsx
  src/Pages/MyPage/UserInfoSection.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/Saved/index.tsx
  src/Router/index.tsx
Labels: 👤 회원정보

#228 SP-566 유저의 최근 출석일 및 스터디 출석요일 API 구현
  src/Mocks/data/mockStudies.ts
  src/Types/study.ts
Labels: 자동 출석 체크, API

#177 타이포그래피 디자인시스템 반영 (<Heading> -> theme으로 변경)
  src/Components/Common/FormSection/index.tsx
  src/Components/Common/LabelForm/index.tsx
  src/Pages/CreateRecruitment/page.tsx
  src/Pages/EditRecruitment/index.tsx
  src/Styles/theme.ts
  src/Styles/typography.ts
Labels: 🖌 style

#232 hotfix: 중복된 임포트 제거
  src/Router/index.tsx
Labels: bug, 라우팅

#220 SP-574 알림 종 useSSE 훅 연결
  package.json
  src/Components/AlarmInBox/AlarmPreview/index.tsx
  src/Components/AlarmInBox/index.tsx
  src/Components/Banner/index.tsx
  src/Components/Common/PositionToken/index.tsx
  src/Components/Header/AlarmBell/index.tsx
  src/Components/Skeleton/SkeletonRecruitmentCardList/index.tsx
  src/Hooks/notifications/useNotifications.ts
  src/Hooks/useSSE.ts
  src/Mocks/data/mockNotifications.ts
  src/Mocks/handlers/SSEnotification.ts
  src/Mocks/handlers/index.ts
  src/Router/index.tsx
  src/Types/notifications.ts
  yarn.lock
Labels: 종 모양 확인, API

#217 SP-563 사용자 출석 체크 버튼
  src/Components/MemberProfile/MemberProfile.stories.ts
  src/Components/MemberProfile/index.tsx
  src/Hooks/study/useAttendStudyMutation.ts
  src/Mocks/data/mockStudies.ts
  src/Pages/StudyDetail/MemberSection.tsx
  src/Pages/StudyDetail/index.tsx
  src/Types/study.ts
Labels: 자동 출석 체크

#222 SP-572 알림 읽음 처리 API 연결
  src/Components/AlarmInBox/AlarmPreview/index.tsx
  src/Components/AlarmInBox/index.tsx
  src/Components/Header/AlarmBell/index.tsx
  src/Hooks/notifications/useReadNotification.ts
  src/Mocks/data/mockNotifications.ts
  src/Mocks/handlers/SSEnotification.ts
  src/Router/index.tsx
Labels: 종 모양 확인, API

#237 SP-608 모집공고 상세 페이지 2.0 UI 반영
  src/Components/Accordion/index.tsx
  src/Components/Common/Divider/RowDivider/index.tsx
  src/Components/Common/InfoField/index.tsx
  src/Hooks/study/useApplyStudyMutation.ts
  src/Pages/RecruitmentDetail/ApplySection.tsx
  src/Pages/RecruitmentDetail/RecruitInfoSection.tsx
  src/Pages/RecruitmentDetail/RecruitmentInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyProgessInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyProgressSection.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Types/study.ts
Labels: 📄 모집공고 상세

#233 SP-606 알림 페이지 구현
  src/Assets/RightArrow.tsx
  src/Components/Accordion/index.tsx
  src/Components/AccordionList/AccordionList.stories.tsx
  src/Components/AccordionList/index.tsx
  src/Components/AlarmInBox/AlarmPreview/index.tsx
  src/Components/Common/KeywordForm/index.tsx
  src/Components/Notification/Notification.stories.tsx
  src/Components/Notification/index.tsx
  src/Components/ToggleSwitchList/index.tsx
  src/Components/Topbar/index.tsx
  src/Constants/messages.ts
  src/Layout/MyPageLayout.tsx
  src/Layout/SettingLayout.tsx
  src/Mocks/data/mockNotifications.ts
  src/Pages/CreateRecruitment/page.tsx
  src/Pages/Notifications/index.tsx
  src/Pages/NotificationsSettings/index.tsx
  src/Types/notifications.ts
  src/utils/getText.ts
  src/utils/moveToDest.ts
Labels: 알림 페이지 확인

#242 SP-607 스터디원이 남긴 리뷰 페이지 구현
  src/Apis/review.ts
  src/Assets/icons/twoway.svg
  src/Assets/index.tsx
  src/Components/Accordion/Accordion.stories.ts
  src/Components/Accordion/index.tsx
  src/Components/ReviewScore/ReviewScore.stories.ts
  src/Components/ReviewScore/StarScore/StarScore.stories.ts
  src/Components/ReviewScore/StarScore/index.tsx
  src/Components/ReviewScore/index.tsx
  src/Components/StudyReviews/PeerToPeerReview/PeerToPeerReview.stories.ts
  src/Components/StudyReviews/PeerToPeerReview/Review/Review.stories.ts
  src/Components/StudyReviews/PeerToPeerReview/Review/index.tsx
  src/Components/StudyReviews/PeerToPeerReview/index.tsx
  src/Components/StudyReviews/StudyReviews.stories.ts
  src/Components/StudyReviews/index.tsx
  src/Components/Topbar/index.tsx
  src/Constants/api.ts
  src/Constants/queryString.ts
  src/Hooks/review/useReviews.ts
  src/Layout/ProfileLayout.tsx
  src/Mocks/data/mockReviews.ts
  src/Mocks/handlers/review.ts
  src/Pages/MyPageReviews/index.tsx
  src/Router/index.tsx
  src/Types/review.ts
  src/utils/getText.ts
Labels: 스터디원 리뷰

#240 SP-611 회원정보 탭 API 연결
  src/Apis/study.ts
  src/Apis/user.ts
  src/Hooks/study/useMyPageInfo.ts
  src/Mocks/data/mockMypage.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/study.ts
  src/Mocks/handlers/users.ts
  src/Pages/MyPage/UserInfoSection.tsx
  src/Types/study.ts
Labels: 👤 회원정보, API

#245 SP-617 스터디 생성, 모집공고 생성 API 500 에러 수정
  src/Components/Button/Studies/BigCategoryButton.stories.ts
  src/Components/Button/Studies/BigCategoryButton.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Pages/CreateRecruitment/page.tsx
  src/Pages/Studies/Layout.tsx
  src/Shared/study.ts
Labels: bug, API

#249 fix: dev 브랜치 배포 에러 해결
  src/Components/TemporarySavedCard/TemporarySavedCard.stories.ts
  src/Components/Textarea/ContactUrlInput.stories.ts
  src/Components/Textarea/ContactUrlInput.tsx
  src/Components/Textarea/Mainarea.stories.ts
  src/Components/Textarea/Mainarea.tsx
  src/Components/Textarea/Titlearea.stories.ts
  src/Components/Textarea/Titlearea.tsx
  src/Components/ToggleSwitch/ToggleSwitch.stories.tsx
  src/Components/ToggleSwitchList/ToggleSwitchList.stories.tsx
  src/Hooks/useSSE.ts
  src/Mocks/data/mockNotifications.ts
  src/Mocks/data/mockStudies.ts
  src/Pages/EditRecruitment/EditRecruitmentFetcher.tsx
  src/Pages/EditRecruitment/index.tsx
  src/Pages/Review/index.tsx
  src/Pages/Studies/Layout.tsx
  src/Pages/StudyDetail/index.tsx
  src/index.tsx
Labels: bug, 🎬 배포

#250 fix: dev 배포 시 생긴 bug 해결
  src/Apis/review.ts
  src/Components/AlarmInBox/AlarmInbox.stories.ts
  src/Components/AlarmInBox/AlarmPreview/AlarmPreview.stories.ts
  src/Components/AlarmInBox/AlarmPreview/index.tsx
  src/Components/ApplicantCard/ApplicantCard.stories.ts
  src/Components/Button/Studies/SubmitButton.stories.ts
  src/Components/Common/LabelForm/LabelForm.stories.ts
  src/Components/CustomRadio/CustomRadio.tsx
  src/Components/Header/index.tsx
  src/Components/Heading/index.tsx
  src/Components/MemberProfile/MemberProfile.stories.ts
  src/Components/MemberProfile/index.tsx
  src/Components/ProfileSection/ProfileSection.stories.ts
  src/Components/ReviewQuestion/ReviewQuestion.tsx
  src/Components/Selectbox/ApplicantButton.tsx
  src/Components/Selectbox/ContactButton.tsx
  src/Components/Selectbox/GatherButton.tsx
  src/Components/Selectbox/MaxPeopleButton.tsx
  src/Components/Selectbox/PlatformButton.tsx
  src/Components/Selectbox/PositionButton.tsx
  src/Components/Selectbox/ProgressButton.tsx
  src/Components/Selectbox/SelectBox.tsx
  src/Components/Selectbox/StackSelect.tsx
  src/Components/StudyReviews/PeerToPeerReview/PeerToPeerReview.stories.ts
  src/Components/StudyReviews/StudyReviews.stories.ts
  src/Pages/Review/index.tsx
Labels: bug

#251 Fix: 배포 시 생기는 버그 수정
  src/Components/StudyReviews/PeerToPeerReview/Review/Review.stories.ts
Labels: bug

#247 SP-633 스터디 생성 페이지 출석일 폼 반영
  src/Components/Common/ChipMenu/index.tsx
  src/Components/Common/Grid/index.tsx
  src/Components/Common/Stack/index.tsx
  src/Components/Header/AlarmBell/index.tsx
  src/Components/Header/HeaderWithLogo/index.tsx
  src/Components/Modal/AttendanceModal/index.tsx
  src/Hooks/useAttendanceModal.ts
  src/Pages/Review/index.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/Layout.tsx
  src/Router/index.tsx
  src/Shared/study.ts
  src/Types/study.ts
Labels: 🖋 스터디 생성

#262 release: dev -> main 배포
  src/Pages/StudyDetail/index.tsx
Labels: 🎬 배포

#264 SP-638 husky, lint-staged 설정
  .husky/pre-commit
  package.json
  yarn.lock
Labels: ⚙️ 환경설정, lint

#266 release: dev -> main 배포
  .husky/pre-commit
  package.json
  src/Components/AlarmInBox/AlarmInbox.stories.ts
  src/Components/AlarmInBox/index.tsx
  src/Components/Header/AlarmBell/index.tsx
  src/Hooks/notifications/useNotifications.ts
  src/Hooks/useSSE.ts
  src/Pages/Notifications/index.tsx
  yarn.lock
Labels: 🎬 배포

#269 스터디 지원자 페이지 dev -> main 반영
  src/Components/ApplicantCard/ApplicantCard.stories.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/CircularRate/index.tsx
  src/Constants/messages.ts
  src/Constants/route.ts
  src/Hooks/notifications/useNotifications.ts
  src/Mocks/data/mockStudies.ts
  src/Pages/Applicants/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/Types/study.ts
Labels: 🎬 배포

#267 알림 페이지 및 알림설정 페이지 버그 수정
  src/Components/Common/ChipMenu/index.tsx
  src/Components/ToggleSwitch/ToggleSwitch.stories.tsx
  src/Components/ToggleSwitch/index.tsx
  src/Components/ToggleSwitchList/index.tsx
  src/Hooks/notifications/useNotifications.ts
  src/Pages/Notifications/index.tsx
  src/Pages/NotificationsSettings/KeywordsSettingForm.tsx
  src/Pages/NotificationsSettings/index.tsx
  src/Pages/Saved/index.tsx
  src/store/notificationSettingClicked.ts
  src/utils/axios.ts
Labels: bug, 알림 페이지 확인, ⏰ 알림 설정

#276 요일 정보 표시 업데이트 배포
  src/Pages/StudyDetail/index.tsx
Labels: 🎬 배포

#279 타입 에러 수정 후 재배포
  src/Hooks/useAttendanceModal.ts
  src/Shared/study.ts
  src/Types/study.ts
Labels: 🎬 배포

#281 스터디 출석 요일 필드 접근시 null check 추가
  src/Pages/StudyDetail/index.tsx
Labels: 🎬 배포

#287 up svg 이미자 맟 관련 컴포넌트 수정 후 배포
  src/Assets/icons/up.svg
  src/Components/DropdownFilter/index.tsx
  src/Components/UtilityButtons/index.tsx
  src/Pages/Recruitments/index.tsx
Labels: 🎬 배포

#289 스택 모달에서 chip 영역이 overflow 되었을 시, scroll이 되도록 수정
  src/Components/Modal/StackModal/index.tsx
Labels: bug, 🎬 배포

#294 SP-649 스터디 리뷰 요청 버튼 표시
  src/Components/Common/Button/index.tsx
  src/Components/Common/Divider/RowDivider/index.tsx
  src/Components/Common/Grid/index.tsx
  src/Components/Common/InputText/index.tsx
  src/Components/Common/LabelForm/LabelForm.stories.ts
  src/Components/Common/LabelForm/index.tsx
  src/Components/Common/Stack/index.tsx
  src/Components/MemberProfile/MemberProfile.stories.ts
  src/Components/MemberProfile/index.tsx
  src/Components/Selectbox/CustomSelect.tsx
  src/Pages/Studies/Layout.tsx
  src/Pages/StudyDetail/MemberSection.tsx
  src/Pages/StudyDetail/index.tsx
Labels: 스터디원 리뷰

#298 platformUrl 수정 후 재배포
  src/Components/Common/Stack/index.tsx
  src/Types/study.ts
Labels: bug

#301 메뉴 z-index 수정
  src/Components/MemberProfile/index.tsx
Labels: bug
