Repository Ludo-SMP/ludo-frontend, pull requests merged in 2024-03, with the labels that each got.

#65 스터디 상태페이지 및 지원자 페이지에서 필요한 data를 가져와, 스터디에서의 role(팀장/팀원)에 따라 다른 UI를 보여주는 기능 구현
  package.json
  public/mockServiceWorker.js
  src/Apis/auth.ts
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/App.tsx
  src/Components/ApplicantCard/index.tsx
  src/Components/LoginProvider/index.tsx
  src/Components/MemberProfile/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Components/StudyCardList/index.tsx
  src/Constants/common.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Mocks/browser.ts
  src/Mocks/data/mockAuth.ts
  src/Mocks/data/mockRecruitments.ts
  src/Mocks/data/mockStudies.ts
  src/Mocks/handlers/auth.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/handlers/study.ts
  src/Mocks/utils/getData.ts
  src/Pages/Applicants/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/StudyDetail/MemberSection/index.tsx
  src/Pages/StudyDetail/StudyInfoSection/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Shared/dummy.ts
  src/Types/study.ts
  src/index.tsx
  src/store/study.ts
  src/store/user.ts
  src/utils/axios.ts
  src/utils/propertyConverter.ts
  yarn.lock
Labels: 🔎 스터디 조회

#67 fix: 스터디 생성페이지 api 연결
  src/Components/Button/Studies/SubmitButton.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Components/Selectbox/MaxPeopleButton.tsx
  src/Components/Selectbox/PlatformButton.tsx
  src/Components/Selectbox/ProgressButton.tsx
  src/Components/StudyCard/index.tsx
  src/Components/StudyCardList/index.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Types/studies.ts
  tsconfig.json
Labels: api 연결

#74 스터디 지원하는 기능, 스터디 지원 결과(지원 완료, 지원 실패)에 따른 모달을 보여주는 기능, 카카오 회원가입/로그인/로그아웃 기능 구현
  public/mockServiceWorker.js
  src/Apis/auth.ts
  src/Apis/recruitment.ts
  src/Apis/stack.ts
  src/Apis/study.ts
  src/Components/Button/CreateButton/index.tsx
  src/Components/CardListInfo/index.tsx
  src/Components/Common/Button/index.tsx
  src/Components/Common/Chip/index.tsx
  src/Components/Common/Modal/index.tsx
  src/Components/Header/SignButtonSection/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/NotFound/index.tsx
  src/Components/PopularCardList/index.tsx
  src/Components/PopularRecruitmentCardList/index.tsx
  src/Components/RecruitmentCard/Position/index.tsx
  src/Components/RecruitmentCard/Tool/index.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/SocialLogin/index.tsx
  src/Constants/Router_Path.ts
  src/Constants/StatusCodes.ts
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Mocks/browser.ts
  src/Mocks/data/mockAuth.ts
  src/Mocks/handlers/auth.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/handlers/study.ts
  src/Pages/Login/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/SignUp/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Pages/StudyList/index.tsx
  src/Shared/dummy.ts
  src/Styles/styled.d.ts
  src/Styles/theme.ts
  src/Types/auth.ts
  src/Types/message.ts
  src/Types/study.ts
  src/index.tsx
  src/store/auth.ts
  src/store/position.ts
  src/utils/axios.ts
  src/utils/propertyConverter.ts
Labels: 🖌 style, 👤 로그인, 🔎 스터디 조회, 👤 회원정보, 🙋🏻‍♂️ 스터디 지원, 📄 모집공고 상세

#75 수정사항 수정& modal data react query 적용
  src/Apis/stack.ts
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Modal/ModalContent/FilterContent.tsx
  src/Components/Modal/ModalContent/ModalContent.tsx
  src/Components/Modal/ModalContent/StackContent.tsx
  src/Components/Modal/Modalitem/Modalitem.tsx
  src/Components/Modal/StackModal.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Components/Selectbox/MaxPeopleButton.tsx
  src/Components/Selectbox/PlatformButton.tsx
  src/Components/Selectbox/PositionButton.tsx
  src/Constants/queryString.ts
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/GatherStudy.tsx
  src/Types/studies.ts
  src/store/stack.ts
  src/utils/axios.ts
Labels: 수정

#78 팀장이 스터디 지원을 수락/거부하는 로직 구현
  src/Apis/study.ts
  src/App.tsx
  src/Assets/images/logo.png
  src/Assets/index.tsx
  src/Components/ApplicantCard/index.tsx
  src/Components/CardListInfo/index.tsx
  src/Components/Common/Chip/index.tsx
  src/Components/Common/StudyToken/index.tsx
  src/Components/Header/StudyButtonSection/index.tsx
  src/Components/Header/index.tsx
  src/Components/MemberCard/index.tsx
  src/Components/MemberProfile/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Components/RecruitmentCard/PositionSection/index.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Constants/StatusCodes.ts
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Mocks/data/mockStudies.ts
  src/Mocks/handlers/auth.ts
  src/Mocks/handlers/study.ts
  src/Mocks/utils/getData.ts
  src/Pages/Applicants/index.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/StudyDetail/MemberSection/index.tsx
  src/Pages/StudyDetail/StudyInfoSection/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Providers/LoginProvider/index.tsx
  src/Providers/QueryProvider/index.tsx
  src/Shared/category.ts
  src/Types/study.ts
  src/store/position.ts
  src/utils/axios.ts
  src/utils/date.ts
  src/utils/propertyConverter.ts
Labels: 🙋🏻‍♂️ 스터디 지원, 📋 스터디 상태, 🎬 팀장, 👥 스터디 모집

#84 마이페이지에서 원하는 My Study 및 임시 저장글 조회, 스터디 지원 취소 기능 구현
  src/Apis/auth.ts
  src/Apis/study.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/Common/ChipMenu/index.tsx
  src/Components/Common/Dropdown/index.tsx
  src/Components/Common/InfoField/index.tsx
  src/Components/Common/InputText/iindex.tsx
  src/Components/Common/StudyToken/index.tsx
  src/Components/Header/SignButtonSection/index.tsx
  src/Components/Header/StudyButtonSection/index.tsx
  src/Components/MemberCard/index.tsx
  src/Components/Modal/EditProfileModal/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Components/TemporarySavedCard/index.tsx
  src/Components/TemporarySavedStudyCard/index.tsx
  src/Components/UserCard/index.tsx
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Mocks/data/mockStudies.ts
  src/Mocks/handlers/study.ts
  src/Pages/MyPage/index.tsx
  src/Providers/QueryProvider/index.tsx
  src/Shared/study.ts
  src/Types/study.ts
  src/index.tsx
  src/store/study.ts
  src/utils/axios.ts
  src/utils/date.ts
  src/utils/propertyConverter.ts
Labels: 🔎 스터디 조회, 👤 회원정보, 🙋🏻‍♂️ 스터디 지원, 👩‍🎨 마이페이지, 📋 스터디 상태

#88 스터디 상태 및 지원자 상태 재정의, 스터디 모집 마감, 탈퇴, 삭제 기능 구현
  src/Apis/auth.ts
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/Common/ChipMenu/index.tsx
  src/Components/Common/StudyToken/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Header/SignButtonSection/index.tsx
  src/Components/Header/StudyButtonSection/index.tsx
  src/Components/Header/index.tsx
  src/Components/MemberProfile/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Constants/StatusCodes.ts
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Mocks/data/mockStudies.ts
  src/Mocks/handlers/auth.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/handlers/study.ts
  src/Pages/Applicants/index.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/StudyDetail/StudyInfoSection/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Providers/QueryProvider/index.tsx
  src/Router/index.tsx
  src/Shared/dummy.ts
  src/Shared/study.ts
  src/Types/study.ts
  src/index.tsx
  src/store/study.ts
  src/utils/axios.ts
  src/utils/date.ts
  src/utils/propertyConverter.ts
Labels: 🙋🏻‍♂️ 스터디 지원, 📋 스터디 상태, 👥 스터디 모집, 🔘 스터디 수락/거절, 🏃 스터디 탈퇴, 🗑 스터디 삭제

#91 푸터 수정 및 임시저장 페이지 구현, 임시저장 페이지에서 수정페이지로 이동 구현
  src/Components/Calendar/EndDate.tsx
  src/Components/Footer/Footer.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Components/Selectbox/GatherButton.tsx
  src/Components/Selectbox/StackSelectButton.tsx
  src/Components/Textarea/ContactUrlInput.tsx
  src/Components/Textarea/Mainarea.tsx
  src/Constants/Router_Path.ts
  src/Mocks/browser.ts
  src/Pages/Studies/CreateRecruitment.tsx
  src/Pages/Studies/GatherStudy.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Pages/Studies/Save.tsx
  src/Pages/Studies/SaveStudy.tsx
  src/Router/index.tsx
  src/index.tsx
Labels: 🖌 style, api 연결, 임시저장

#95 메인페이지 및 모집공고 페이지 수정된 디자인 반영, 수정된 API 명세 반영
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Assets/Alarm.tsx
  src/Assets/icons/DownBold.tsx
  src/Assets/icons/RightBold.tsx
  src/Assets/icons/UpBold.tsx
  src/Assets/icons/alarm.svg
  src/Assets/index.tsx
  src/Components/CardListInfo/index.tsx
  src/Components/Common/Chip/index.tsx
  src/Components/Common/Image/index.tsx
  src/Components/Common/PositionToken/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/DropdownFilters/index.tsx
  src/Components/Header/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/PopularRecruitmentCardList/index.tsx
  src/Components/RecruitmentCard/Tool/index.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/UtilityButtons/index.tsx
  src/Mocks/data/mockRecruitments.ts
  src/Mocks/data/mockStack.ts
  src/Mocks/handlers/recruitment.ts
  src/Pages/Main/index.tsx
  src/Pages/RecruitmentDetail/RecruitmentInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyProgessInfoSection/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/StudyDetail/StudyInfoSection/index.tsx
  src/Router/index.tsx
  src/Shared/category.ts
  src/Shared/dummy.ts
  src/Shared/study.ts
  src/Styles/theme.ts
  src/Types/study.ts
  src/index.tsx
  src/store/category.ts
  src/store/filter.ts
  src/utils/axios.ts
Labels: 🖌 style, 🔎 스터디 조회, 📋 스터디 상태

#96 모집공고 모아보기 페이지 필터 전역 관리, 프로필 모달 마크업 구현
  src/Apis/recruitment.ts
  src/Components/Common/Dropdown/index.tsx
  src/Components/DropdownFilter/DropdownItem/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/DropdownFilters/index.tsx
  src/Components/Modal/EditProfileModal/index.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Mocks/browser.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/utils/getData.ts
  src/Mocks/utils/getQueryParams.ts
  src/Pages/RecruitmentDetail/StudyProgessInfoSection/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Providers/QueryProvider/index.tsx
  src/Shared/study.ts
  src/Types/study.ts
  src/index.tsx
  src/store/filter.ts
Labels: 🔎 스터디 조회, 👩‍🎨 마이페이지

#102 스터디의 상태에 따라 다른 UI 요소를 보여주는 기능 구현
  src/Apis/auth.ts
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Apis/user.ts
  src/Components/Button/Studies/ProgressButton.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Common/Chip/index.tsx
  src/Components/Footer/Footer.tsx
  src/Components/Header/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/utils/getData.ts
  src/Pages/Main/index.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/Studies/CreateRecruitment.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/ModifyRecruitment.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Pages/StudyDetail/MemberSection/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Providers/LoginProvider/index.tsx
  src/Types/study.ts
  src/store/position.ts
  src/utils/axios.ts
  src/utils/date.ts
Labels: 📋 스터디 상태

#103 타입 에러 수정 및 불필요한 코드 제거
  src/Pages/Studies/ModifyRecruitment.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Types/studies.ts
Labels: bug

#105 배포를 위한 타입 에러 정리
  src/Apis/study.ts
  src/Apis/user.ts
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/DropdownFilter/DropdownItem/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Selectbox/StackSelectButton.tsx
  src/Mocks/data/mockAuth.ts
  src/Mocks/data/mockRecruitments.ts
  src/Mocks/data/mockStack.ts
  src/Mocks/data/mockStudies.ts
  src/Mocks/handlers/auth.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/handlers/study.ts
  src/Pages/StudyDetail/MemberSection/MemberCarousel/index.tsx
  src/Shared/category.ts
Labels: 🎬 배포

#106 타입 에러 처리 후, 배포를 위한 merge
  src/Apis/study.ts
  src/Apis/user.ts
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/DropdownFilter/DropdownItem/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Selectbox/StackSelectButton.tsx
  src/Mocks/data/mockAuth.ts
  src/Mocks/data/mockRecruitments.ts
  src/Mocks/data/mockStack.ts
  src/Mocks/data/mockStudies.ts
  src/Mocks/handlers/auth.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/recruitment.ts
  src/Mocks/handlers/study.ts
  src/Pages/StudyDetail/MemberSection/MemberCarousel/index.tsx
  src/Shared/category.ts
Labels: 🎬 배포

#107 배포를 위한 타입 에러 정리
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Components/Modal/Modalitem/Modalitem.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/Selectbox/ApplicantButton.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Components/Selectbox/ContactButton.tsx
  src/Components/Selectbox/GatherButton.tsx
  src/Components/Selectbox/PlatformButton.tsx
  src/Components/Selectbox/ProgressButton.tsx
  src/Components/Textarea/ContactUrlInput.tsx
  src/Components/Textarea/Mainarea.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Constants/Validation.tsx
  src/Mocks/browser.ts
  src/Mocks/utils/getData.ts
  src/Pages/Studies/CreateRecruitment.tsx
Labels: 🎬 배포

#108 타입 에러 처리 후, 배포를 위한 merge
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Components/Modal/Modalitem/Modalitem.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/Selectbox/ApplicantButton.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Components/Selectbox/ContactButton.tsx
  src/Components/Selectbox/GatherButton.tsx
  src/Components/Selectbox/PlatformButton.tsx
  src/Components/Selectbox/ProgressButton.tsx
  src/Components/Textarea/ContactUrlInput.tsx
  src/Components/Textarea/Mainarea.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Constants/Validation.tsx
  src/Mocks/browser.ts
  src/Mocks/utils/getData.ts
  src/Pages/Studies/CreateRecruitment.tsx
Labels: 🎬 배포

#109 배포를 위한 타입 에러 정리
  src/Apis/auth.ts
  src/Apis/recruitment.ts
  src/Apis/stack.ts
  src/Apis/study.ts
  src/Apis/user.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/Common/Chip/index.tsx
  src/Components/Common/Modal/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Header/SignButtonSection/index.tsx
  src/Components/Header/StudyButtonSection/index.tsx
  src/Components/Header/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/Modal/EditProfileModal/index.tsx
  src/Components/NotFound/index.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/SocialLogin/index.tsx
  src/Components/UserCard/index.tsx
  src/Pages/Applicants/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Providers/LoginProvider/index.tsx
Labels: 🎬 배포

#110 타입 에러 처리 후, 배포를 위한 merge
  src/Apis/auth.ts
  src/Apis/recruitment.ts
  src/Apis/stack.ts
  src/Apis/study.ts
  src/Apis/user.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/Common/Chip/index.tsx
  src/Components/Common/Modal/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Header/SignButtonSection/index.tsx
  src/Components/Header/StudyButtonSection/index.tsx
  src/Components/Header/index.tsx
  src/Components/Modal/ApplyModal/index.tsx
  src/Components/Modal/EditProfileModal/index.tsx
  src/Components/NotFound/index.tsx
  src/Components/RecruitmentCard/index.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/SocialLogin/index.tsx
  src/Components/UserCard/index.tsx
  src/Pages/Applicants/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/MyPage/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Pages/StudyDetail/index.tsx
  src/Providers/LoginProvider/index.tsx
Labels: 🎬 배포

#111 nelify 404 에러 해결을 위한 netlify.toml 설정
  netlify.toml
  public/_redirects
Labels: 🎬 배포

#112 nelify 404 에러 해결을 위한 netlify.toml 설정
  netlify.toml
  public/_redirects
Labels: 🎬 배포

#113 nelify 404 에러 해결을 위한 netlify.toml 설정
  netlify.toml
Labels: 🎬 배포

#114 nelify 404 에러 해결을 위한 netlify.toml 설정
  netlify.toml
Labels: 🎬 배포

#115 레이아웃 수정
  index.html
  src/Apis/studies.ts
  src/Components/Footer/Footer.tsx
  src/Components/Header/index.tsx
  src/Components/Modal/Modalitem/Modalitem.tsx
  src/Components/Selectbox/ProgressButton.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Pages/Studies/CreateRecruitment.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/ModifyRecruitment.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/Types/studies.ts
Labels: 🖌 style

#122 불필요한 컴포넌트 제거 및 타입 에러 수정
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Modal/DefaultModal.tsx
  src/Components/Modal/StackModal.tsx
  src/Mocks/handlers/auth.ts
  src/Pages/Studies/CreateRecruitment.tsx
  src/Shared/dummy.ts
Labels: bug

#123 불필요한 컴포넌트 제거 및 타입 에러 수정 후 배포
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Modal/DefaultModal.tsx
  src/Components/Modal/StackModal.tsx
  src/Mocks/handlers/auth.ts
  src/Pages/Studies/CreateRecruitment.tsx
  src/Shared/dummy.ts
Labels: bug, 🎬 배포

#124 에러 코드 수정 및 불필요한 컴포넌트 제거
  src/Components/Modal/ModalContent/StackContent.tsx
  src/Mocks/handlers/study.ts
Labels: bug, 리팩토링

#125 에러 코드 수정 및 불필요한 컴포넌트 제거 후 배포
  src/Components/Modal/ModalContent/StackContent.tsx
  src/Mocks/handlers/study.ts
Labels: 🎬 배포

#127 모집공고 지원 시, 지원 성공 및 실패에 대한 로직 수정 구현
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Hooks/study/useApplyStudyMutation.ts
  src/Pages/RecruitmentDetail/index.tsx
Labels: 🙋🏻‍♂️ 스터디 지원

#128 모집공고 지원 시, 지원 성공 및 실패에 대한 로직 수정된 사항 반영 후 배포
  src/Components/Calendar/EndDate.tsx
  src/Components/Calendar/ProgressPeriod.tsx
  src/Components/Textarea/Titlearea.tsx
  src/Hooks/study/useApplyStudyMutation.ts
  src/Pages/RecruitmentDetail/index.tsx
Labels: 🎬 배포

#131 스터디 탈퇴 및 모집마감 기능 구현 완료
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Hooks/study/useAcceptApplyMutation.ts
  src/Hooks/study/useApplyStudyMutation.ts
  src/Hooks/study/useCancelAppyMutation.ts
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/StudyDetail/index.tsx
Labels: 📋 스터디 상태, 🏃 스터디 탈퇴

#132 스터디 모집 마감 기능, 스터디 탈퇴 기능 수정 후 배포
  src/Apis/recruitment.ts
  src/Apis/study.ts
  src/Components/ApplicantCard/index.tsx
  src/Components/MyStudyCard/index.tsx
  src/Constants/api.ts
  src/Constants/messages.ts
  src/Constants/queryString.ts
  src/Hooks/study/useAcceptApplyMutation.ts
  src/Hooks/study/useApplyStudyMutation.ts
  src/Hooks/study/useCancelAppyMutation.ts
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/StudyDetail/index.tsx
Labels: 📋 스터디 상태, 👥 스터디 모집, 🏃 스터디 탈퇴, 🎬 배포

#138 회원가입, 로그인 실패 시 이동하는 페이지 구현, 사용자 피드백을 위한 UT 배너 구현
  src/Assets/icons/article.svg
  src/Assets/images/background.png
  src/Assets/images/banner1.png
  src/Assets/images/banner2.png
  src/Assets/images/character1.png
  src/Assets/images/character2.png
  src/Assets/images/character3.png
  src/Assets/images/logo3.png
  src/Assets/index.tsx
  src/Components/Common/DropdownItem/index.tsx
  src/Components/Dropdown/index.tsx
  src/Components/Header/index.tsx
  src/Components/NotFoundResult/index.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Components/UTbanner/index.tsx
  src/Components/UserCard/index.tsx
  src/Constants/messages.ts
  src/Constants/route.ts
  src/Pages/Applicants/index.tsx
  src/Pages/Login/index.tsx
  src/Pages/LoginFail/index.tsx
  src/Pages/RecruitmentDetail/RecruitmentInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyProgessInfoSection/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/SignUp/index.tsx
  src/Pages/SignUpFail/index.tsx
  src/Pages/Studies/CreateRecruitment.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/ModifyRecruitment.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Pages/Studies/SaveStudy.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/Types/studies.ts
Labels: 👤 로그인, 🔎 스터디 조회, 👤 회원정보, 📋 스터디 상태

#139 회원가입, 로그인 실패 시 이동하는 페이지 구현, 사용자 피드백을 위한 UT 배너 구현 후 배포
  README.md
  src/Assets/icons/article.svg
  src/Assets/images/background.png
  src/Assets/images/banner1.png
  src/Assets/images/banner2.png
  src/Assets/images/character1.png
  src/Assets/images/character2.png
  src/Assets/images/character3.png
  src/Assets/images/logo3.png
  src/Assets/index.tsx
  src/Components/Common/DropdownItem/index.tsx
  src/Components/Dropdown/index.tsx
  src/Components/Header/index.tsx
  src/Components/NotFoundResult/index.tsx
  src/Components/Selectbox/BigCategoryButton.tsx
  src/Components/UTbanner/index.tsx
  src/Components/UserCard/index.tsx
  src/Constants/messages.ts
  src/Constants/route.ts
  src/Pages/Applicants/index.tsx
  src/Pages/Login/index.tsx
  src/Pages/LoginFail/index.tsx
  src/Pages/RecruitmentDetail/RecruitmentInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyBasicInfoSection/index.tsx
  src/Pages/RecruitmentDetail/StudyProgessInfoSection/index.tsx
  src/Pages/RecruitmentDetail/index.tsx
  src/Pages/SignUp/index.tsx
  src/Pages/SignUpFail/index.tsx
  src/Pages/Studies/CreateRecruitment.tsx
  src/Pages/Studies/CreateStudy.tsx
  src/Pages/Studies/ModifyRecruitment.tsx
  src/Pages/Studies/ModifyStudy.tsx
  src/Pages/Studies/SaveStudy.tsx
  src/Pages/StudyDetail/index.tsx
  src/Router/index.tsx
  src/Types/studies.ts
Labels: 🎬 배포

#141 스터디 직접 생성하기 버튼 클릭 시, 동일한 모달이 2개 보여지는 버그 해결
  README.md
  src/Components/NotFoundResult/index.tsx
Labels: bug, 🖋 스터디 생성

#142 스터디 직접 생성하기 버튼 클릭 시, 동일한 모달이 2개 보여지는 버그 수정 후 배포
  README.md
  package.json
  src/Components/NotFoundResult/index.tsx
  yarn.lock
Labels: bug, 🎬 배포

#144 모달을 활성화 시키는 로직 추가 후 배포
  src/Components/NotFoundResult/index.tsx
Labels: 🎬 배포

#146 NotFoundComponent에서 미사용 변수 제거 후 배포
  src/Components/NotFoundResult/index.tsx
Labels: 🎬 배포

#148 메인페이지, 모아보기 페이지 banner, footer, header 반응형 구현
  src/Components/Banner/index.tsx
  src/Components/DropdownFilter/DropdownItem/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Footer/index.tsx
  src/Components/Header/SignButtonSection/index.tsx
  src/Components/Header/index.tsx
  src/Components/RecruitmentCardList/index.tsx
  src/Components/UTbanner/index.tsx
  src/Components/UtilityButtons/index.tsx
  src/Pages/Main/index.tsx
  src/Pages/Recruitments/index.tsx
Labels: 🖌 style
