Repository Ludo-SMP/ludo-frontend, pull requests merged in 2024-05, with the labels that each got.

#167 테스트 환경 설정
  jest.config.ts
  jest.setup.ts
  package.json
  src/Components/Common/Button/Button.spec.tsx
  src/__test__/Render.tsx
  tsconfig.json
  yarn.lock
Labels: ⚙️ 환경설정

#168 feat: 스택 검색 기능 구현
  src/Assets/icons/setting.svg
  src/Assets/icons/studyThumbnail.svg
  src/Assets/index.tsx
  src/Components/Common/ChipMenu/index.tsx
  src/Components/Common/InfoField/index.tsx
  src/Components/Common/InputText/index.tsx
  src/Components/Common/StudyToken/index.tsx
  src/Components/Common/TechStack/index.tsx
  src/Components/DropdownFilter/index.tsx
  src/Components/Footer/index.tsx
  src/Components/Icons.mdx
  src/Components/Modal/EditProfileModal/EditProfileModal.stories.ts
  src/Components/Modal/EditProfileModal/index.tsx
  src/Components/Modal/StackModal/StackModal.stories.ts
  src/Components/Modal/StackModal/index.tsx
  src/Components/MyStudyCard/MyStudyCard.stories.ts
  src/Components/MyStudyCard/index.tsx
  src/Components/TemporarySavedCard/index.tsx
  src/Components/UserCard/index.tsx
  src/Hooks/useDebounce.ts
  src/Pages/MyPage/index.tsx
  src/Pages/Recruitments/index.tsx
  src/Shared/study.ts
  src/Types/study.ts
  src/store/study.ts
  src/utils/axios.ts
Labels: 🔎 스터디 조회, 🖋 스터디 생성

#172 build: 유닛 테스트를 자동으로 수행하기 위한 GA 설정
  .github/workflows/test.yaml
  .node-version
Labels: ⛏ 테스트

#173 스택 모달 이미지가 storybook에서 정상적으로 표시되지 않는 문제 해결
  .storybook/preview.tsx
  package.json
  src/App.tsx
  src/Mocks/data/mockStack.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/stacks.ts
  yarn.lock
Labels: documentation, storybook

#179 아코디언 컴포넌트 구현
  src/Assets/SelectArrow.tsx
  src/Components/Accordion/Accordion.stories.ts
  src/Components/Accordion/index.tsx
  src/Styles/theme.ts
Labels: 알림 페이지 확인

#199 SP-543 신규 페이지 라우팅 설정
  src/Components/Footer/index.tsx
  src/Components/Header/Gnb/index.tsx
  src/Components/Header/StudyButtonSection/index.tsx
  src/Components/Header/index.tsx
  src/Constants/route.ts
  src/Hooks/study/useDeleteStudyMutation.ts
  src/Hooks/study/useLeaveStudyMutation .ts
  src/Router/index.tsx
Labels: 라우팅

#187 SP-530 사이드바 컴포넌트 구현
  src/Components/Sidebar/Sidebar.stories.ts
  src/Components/Sidebar/Sidebar.tsx
  src/Components/Sidebar/Tab.stories.ts
  src/Components/Sidebar/Tab.tsx
Labels: 👩‍🎨 마이페이지

#193 SP-534 프로필 섹션 컴포넌트 구현
  src/Components/ProfileSection/ProfileSection.stories.ts
  src/Components/ProfileSection/ProfileSection.tsx
Labels: 👩‍🎨 마이페이지

#184 평가 문항 컴포넌트(ReviewQuestion) 구현
  src/Components/CustomRadio/CustomRadio.stories.ts
  src/Components/CustomRadio/CustomRadio.tsx
  src/Components/ReviewQuestion/ReviewQuestion.stories.ts
  src/Components/ReviewQuestion/ReviewQuestion.tsx
Labels: 사용자 리뷰평가

#189 아코디언 리스트 컴포넌트 구현
  src/Components/Accordion/index.tsx
  src/Components/AccordionList/AccordionList.stories.tsx
  src/Components/AccordionList/index.tsx
  src/Components/Button/Studies/MaxPeopleButton.tsx
  src/Components/Button/Studies/StackButton.tsx
  src/Components/Modal/ModalContent/ModalButton/SelectButton.tsx
  src/Components/Selectbox/MaxPeopleButton.tsx
  src/Pages/CreateRecruitment/page.tsx
  src/Pages/Studies/Layout.tsx
  src/Styles/styled.d.ts
  src/Styles/theme.ts
Labels: 알림 페이지 확인

#212 [SP-571] 알림 설정 API 구현
  src/Apis/notification.ts
  src/Constants/api.ts
  src/Constants/queryString.ts
  src/Hooks/notifications/useEditNotificationsKeywords.ts
  src/Hooks/notifications/useNotificationsSetting.ts
  src/Hooks/notifications/useOnOffNotifications.ts
  src/Mocks/data/mockNotifications.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/notifications.ts
  src/Types/notifications.ts
Labels: ⏰ 알림 설정

#211 출석 체크 API 구현
  src/Apis/study.ts
  src/Constants/api.ts
  src/Mocks/handlers/study.ts
Labels: 자동 출석 체크, API

#203 SP-562 스터디원 리뷰 평가 제출 API
  src/Apis/review.ts
  src/Constants/api.ts
  src/Mocks/handlers/index.ts
  src/Mocks/handlers/review.ts
  src/Types/review.ts
Labels: 사용자 리뷰평가, API
